- id: '1637359735435'
  alias: HA GitHub
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /bin/bash /config/scripts/ha_gitpush.sh
  - service: notify.telegram_pascal
    data:
      message: Sauveagarde GITHUB
  mode: single
