- platform: generic
  name: "Portier"
  still_image_url: http://192.168.0.175/cgi-bin/snapshot.cgi
  authentication: digest
  stream_source: !secret portierdUrlRtsp
  username: !secret portierUser
  password: !secret portierPassword

- platform: push
  name: MotionEyelastmotion
  webhook_id: motioneye_webkook_portier
