# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
mobile_app:

lovelace:
  resources:
    - url: /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /local/community/lovelace-climate-mode-entity-row/climate-mode-entity-row.js
      type: module

frontend:
  extra_module_url:
    - /local/custom-ui/custom-ui.js

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
utility_meter: !include utility_meter.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
shell_command: !include shellCommand.yaml
notify: !include notify.yaml
climate: !include climate.yaml
switch: !include switchs.yaml
input_text: !include input_text.yaml
light: !include light.yaml
input_number: !include input_number.yaml
input_datetime: !include input_dateTime.yaml
input_boolean: !include input_boolean.yaml
vacuum: !include aspirateurs.yaml
camera: !include cameras.yaml
device_tracker: !include deviceTracker.yaml

homeassistant:
  customize: !include customize.yaml

wake_on_lan:

########################################## DATABASE ##################################################################################################
recorder:
  db_url: !secret url_posgres_db
  auto_purge: true
  purge_keep_days: 65
  include:
    domains:
      - sensor
      - switch
      - binary_sensor
  exclude:
    domains:
      - weblink
      - updater
      - input_boolean
      - input_number
      - input_select
      - input_text
      - light
      - media_player
      - sun
      - timer
      - weather
      - camera
      - automation
    entity_globs:
      - sensor.weather_*
      - sensor.sensor.ups_*
      - binary_sensor.huawei_*
      - switch.echo_*
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - sensor.hacs
      - sensor.time
      - sensor.date_time_iso # Don't record date and time
      - sensor.yr_symbol # Ignore this as well
      - group.weather # Don't save weather
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeAssistant
#   username: !secret influxdb_user
#   password: !secret influxdb_pwd
#   max_retries: 3
#   default_measurement: state
#   tags_attributes:
#     - friendly_name
#     - hidden
#   exclude:
#     domains:
#       - automation
#       - group

# Text to speech
tts:
  - platform: google_translate

discovery:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

mqtt:
  broker: core-mosquitto
  username: !secret mosquitto_username
  password: !secret mosquitto_password
  discovery: true

#Zwave mise à jour openzwave
# zwave:
#  usb_path: /dev/ttyACM0
#  config_path: /config/z-wave/open-zwave/config

#Google Agenda
google:
  client_id: !secret google_id
  client_secret: !secret google_key

########################################## TELEGRAM ##################################################################################################

#TELEGRAM
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret telegram_pascal_id
      - !secret telegram_stephanie_id
      - !secret telegram_eloise_id

########################################## ALEXA ##################################################################################################

# # Alexa media player set up
# alexa_media:
#   accounts:
#     - email: !secret username_amazon
#       password: !secret password_amazon
#       url: "amazon.fr"

########################################## DOORBIRD ##################################################################################################

#Doorbird
doorbird:
  devices:
    - host: !secret DOORBIRD_IP
      username: !secret DOORBIRD_USERNAME
      password: !secret DOORBIRD_PASSWORD
      token: !secret Token
      name: Portier
      events:
        - carillon
        - une_personne_sonne
        - ouvrir_portail
        - unit_2_bell

# configuration SMS avec cle
# sms:
#   device: /dev/ttyUSB1
########################################## OVH ##################################################################################################
# ovh:
#   domain: !secret ovh_domain
#   username: !secret ovh_username
#   password: !secret ovh_password

########################################## MODEM GSM ##################################################################################################

huawei_lte:
  - url: https://192.169.8.1
    username: !secret usernamegsm
    password: !secret motdepassegsm
    notify:
      recipient:
        - !secret stephanie_number
        - !secret pascal_number
########################################## REST COMMAND ##################################################################################################
rest_command:
  truenas_shutdown:
    url: http://192.168.0.140/api/v2.0/system/shutdown/
    method: post
    username: !secret truenas_user
    password: !secret truenas_password
    headers:
      content-Type: application/json

  launch_doorbird_on_android_tab:
    url: !secret fullykiosk
    method: POST

  fully_kiosk_cuisine_cmd:
    url: !secret fully_kiosk_cuisine_cmd
  fully_kiosk_cuisine_playsound:
    url: !secret fully_kiosk_cuisine_playsound

########################################## ALARME ##################################################################################################

alarm_control_panel:
  - platform: manual
    name: Alarme maison
    code: "1234"
    disarm_after_trigger: false # Après la durée du trigger time, l'alarme revient en état armée

    disarmed:
      trigger_time: 0 # Le fait de de désarmer arrête immédiatement l'alarme

    armed_night:
      arming_time: 1 # temps en secondes pour quitter la maison
      delay_time: 0 # temps en secondes pour désarmer avant déclenchement
      trigger_time: 60 # temps en secondes pendant lequel la sirene retentit (60 secondes dans la nuit)

    armed_home:
      arming_time: 60 # L'alarme s'activera au bout de 60 secondes
      delay_time: 10 # Lorsqu'elle est activée, elle se declenchera au bout de 10 secondes
      trigger_time: 300 # La sirène s'arrtera au bout de 5 minutes

    armed_away: #Mode activiation manuelle (quand on est dans la maison et on part)
      arming_time: 60
      delay_time: 10
      trigger_time: 300
########################################## ANDROID TV ##################################################################################################

media_player:
  - platform: androidtv
    adb_server_ip: 192.168.0.90
    name: Tab Cuisine_old
    host: 192.168.0.168

  - platform: androidtv
    adb_server_ip: 192.168.0.241
    name: Tab Cuisine
    host: 192.168.0.168

person:
  - name: Pascal
    id: ada6789
    device_trackers:
      - device_tracker.oneplus_pascal
