- platform: ping
  count: 5
  consider_home: 600
  hosts:
    eloise_telephone: 192.168.0.45
    clarence_telephone: 192.168.0.42
    stephanie_telephone: 192.168.0.43
    pascal_telephone: 192.168.0.239
